version: '3'
services:

  blog-fpm:
    build:
      context: .
      dockerfile: "Dockerfile.fpm-pdo"
    env_file:
      - "mysql.env"
    depends_on:
      - "mariadb"
    links:
      - "mariadb:mariadb"
    volumes:
      - "./craft:/usr/share/nginx/html"
    working_dir: "/usr/share/nginx/html"

  blog-static:
    image: "nginx"
    ports:
      - "80:80"
    volumes:
      - "./public:/usr/share/nginx/html"
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    links:
      - "blog-fpm:blog-fpm"

  mariadb:
    image: "mariadb"
    env_file:
      - "mysql.env"
    volumes:
      - "./db:/var/lib/mysql"